name: continuous-deploy-by-docker

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2

      - name: create root env file
        run: |
          rm .env
          touch .env
          echo "${{ secrets.ROOT_ENV }}" > .env

      - name: create client env file
        run: |
          cd client
          touch .env.production
          echo "${{ secrets.CLIENT_ENV }}" > .env.production

      - name: create env file
        run: |
          cd server
          touch .env.production
          echo "${{ secrets.SERVER_ENV }}" > .env.production

      - name: build image
        run: docker compose build

      - name: push image
        run: |
          docker tag web11-donggle_nginx ghcr.io/isanghaessi/web11-donggle_nginx
          docker tag web11-donggle_client-react ghcr.io/isanghaessi/web11-donggle_client-react
          docker tag web11-donggle_server-express ghcr.io/isanghaessi/web11-donggle_server-express
          docker push ghcr.io/isanghaessi/web11-donggle_nginx
          docker push ghcr.io/isanghaessi/web11-donggle_client-react
          docker push ghcr.io/isanghaessi/web11-donggle_server-express

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /
            mkdir -p donggle-compose
            touch docker-compose.yml
            echo "${{ secrets.COMPOSE_YML }}" > docker-compose.yml
            docker-compose pull
            docker-compose down && docker-compose up
