name: continuous-deploy-by-docker

on:
  push:
    branches:
      - test/server-relocation

jobs:
  build-push-pull-down_up:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2

      - name: create root env file
        run: |
          rm .env
          touch .env
          echo "${{ secrets.ROOT_ENV }}" > .env

      - name: create client env file
        run: |
          cd client
          touch .env.production
          echo "${{ secrets.CLIENT_ENV }}" > .env.production

      - name: create env file
        run: |
          cd server
          touch .env.production
          echo "${{ secrets.SERVER_ENV }}" > .env.production

      - name: ghcr login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: build image
        run: docker compose build

      - name: push image
        run: docker compose push

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/Web11-Donggle
            git remote update
            git checkout origin/main
            git reset --hard
            rm .env
            touch .env
            echo "${{ secrets.ROOT_ENV }}" > .env
            cd ./client
            rm .env.production
            touch .env.production
            echo "${{ secrets.CLIENT_ENV }}" > .env.production
            cd ../server
            rm .env.production
            touch .env.production
            echo "${{ secrets.SERVER_ENV }}" > .env.production
            cd ..
            docker login ghcr.io/ -u ${{ secrets.USERNAME }} -p ${{ secrets.ACCESS_TOKEN }}
            docker-compose pull
            docker-compose down
            docker-compose up -d
